[package]
name = "rpkl_cli"
version = "0.1.0"
edition = "2024"


[[bin]]
name = "rpkl"
path = "src/main.rs"
doc = false

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
rpkl = { path = "../..", features = ["codegen-experimental"] }
